include $(GNUSTEP_MAKEFILES)/common.make
OBJCFLAGS = -fobjc-arc
LDFLAGS = -ldispatch
TOOL_NAME = CallByMeaningDemo
CallByMeaningDemo_OBJC_FILES = FoundMethod.m MethodFinder.m MyClass1.m MyClass2.m main.m
include $(GNUSTEP_MAKEFILES)/tool.make

