on:
  [push]
name: Run under GNUstep on Ubuntu 20.10
jobs:
  testbuild:
    name: Building GNUstep
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@master
      - name: Build GNUstep
        shell: bash
        run: |
          git clone https://github.com/plaurent/gnustep-build
          cd gnustep-build/
          cd ubuntu-20.10-clang-11.0-runtime-2.0/
          chmod +x GNUstep-buildon-ubuntu2010.sh
          ./GNUstep-buildon-ubuntu2010.sh

      - name: Run the project
        shell: bash
        run: |
            source ~/.bashrc
            cat ~/.bashrc
            . /usr/GNUstep/System/Library/Makefiles/GNUstep.sh
            cd src/call-by-meaning-objc
            make
            ls
            ./CallByMeaningDemo
